modLoader = "kotlinforforge"
loaderVersion = "[4.6,)"
license = "All rights reserved (TODO)"
issueTrackerURL = "https://github.com/Bluexin/saoui/issues"

[[mods]]
modId = "mcui" #mandatory
version = "${version}"
displayName = "Modular Customizable User Interface (WIP Name)"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "https://github.com/Bluexin/saoui/wiki"
logoFile = "assets/saoui/textures/logo.png"
credits = "All theme maintainers for building content and TheJackiMonster for the original SAOUI mod"
authors = "Bluexin, Tencao"
description = '''
Customize UI (both HUD and Screens) via resource packs !
'''

[[dependencies.mcui]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.mcui]]
#modId = "architectury"
#mandatory = true
#versionRange = "[8.2.89,)"
#ordering = "AFTER"
#side = "BOTH"
