image: java:8

cache:
  paths:
    - $HOME/.gradle
    - .gradle
    - gradle

before_script:
  # Enable the usage of sources over https
  - apt-get update -yqq
  - apt-get install apt-transport-https -yqq
  # Log the java version
  - java -version

build:
  variables:
    NAME: "Builds stalker"
    MESSAGE: "Project $CI_PROJECT_NAME (branch $CI_BUILD_REF_NAME) build successful: "
    IMG: "https://cdn.discordapp.com/icons/131019825681006592/9df46a9d968c06e8eb264c590cc23a43.jpg"
    DL_LINK: "https://gitlab.com/saomc/saoui-1.10.2/builds/$CI_BUILD_ID/artifacts/browse/artifacts/"
  script:
    - chmod +x gradlew
    - ./gradlew setupCIWorkspace build uploadArchives
    - mkdir artifacts
    - cp build/libs/* artifacts/
    - curl --data "content=$MESSAGE$(git log -1 --pretty=%B) (download at $DL_LINK)&username=$NAME&avatar_url=$IMG" $DISCORD_HOOK
  artifacts:
    paths:
    - artifacts/
