# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="kotlinforforge" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion="[1,)" #mandatory

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="url" #optional

# License
license="All rights reserved"

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="saoui" #mandatory

# The version number of the mod
version="${version}" #mandatory

# A display name for the mod
displayName="SAOUI" #mandatory

# A URL for the "homepage" for this mod, displayed in the mod UI
# displayURL="url" #optional

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="" #optional

# A text field displayed in the mod UI
# credits="" #optional

# A text field displayed in the mod UI
authors="Tencao, Bluexin" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Core functions library for related projects.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.saoui]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="${forge_version}" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"

[[dependencies.saoui]]
modId="minecraft" #mandatory
mandatory=true #mandatory
versionRange="${mc_version}" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"

[[dependencies.saoui]]
modId="saomclib" #mandatory
mandatory=true #mandatory
versionRange="1.4.10" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
